name: "build"

on: 
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Ruby Version"
        options:
          - "2.7.x"
          - "2.7.7"
          - "3.0.8"

env:
  DOCKER_BUILDKIT: 1
  DISABLE_ASSET_SYNC: 1

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     include:
    #       - ruby: 2.7.7
    #         sha256: b38dff2e1f8ce6e5b7d433f8758752987a6b2adfd9bc7571dbc42ea5d04aaaaa
    #       - ruby: 2.7.8
    #         sha256: b38dff2e1f8ce6e5b7d433f8758752987a6b2adfd9bc7571dbc42ea5d04e3e4c

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: test
        if: matrix.ruby == github.event.inputs.version
        run: |
          echo ${{ fromJson(`cat versions.json`) }}
          # echo ${{ github.event.inputs.version }}
          # echo ${{ matrix.ruby }}
          # echo ${{ matrix.sha256 }}
      # -
      #   name: Checkout
      #   uses: actions/checkout@v3
      # -
      #   # Add support for more platforms with QEMU (optional)
      #   # https://github.com/docker/setup-qemu-action
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: 2.7/bullseye
      #     push: true
      #     tags: gendosu/gentest:${{ github.event.inputs.env }}
