name: "build ruby starter"

on: push
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       type: choice
  #       description: "Ruby Version"
  #       options:
  #         - "2.7.x"
  #         - "2.7.7"
  #         - "3.0.8"

env:
  DOCKER_BUILDKIT: 1
  DISABLE_ASSET_SYNC: 1

jobs:
  set-matrix:
    runs-on: ubuntu-latest

    outputs:
      RUBY_VERSION: ${{ steps.set-matrix.outputs.RUBY_VERSION }}
      RUBY_SHA: ${{ steps.set-matrix.outputs.RUBY_SHA }}
      RUBY_DIRS: ${{ steps.set-matrix.outputs.RUBY_DIRS }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: set-matrix
        id: set-matrix
        run: |
          cat versions.json
          # include=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | {"include": .}'`
          RUBY_VERSION=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .ruby'`
          RUBY_SHA=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .sha256'`
          RUBY_DIRS=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .dir'`
          echo "include='${include}'"
          echo "RUBY_VERSION='${RUBY_VERSION}'" >> $GITHUB_OUTPUT
          echo "RUBY_SHA='${RUBY_SHA}'" >> $GITHUB_OUTPUT
          echo "RUBY_DIRS=${RUBY_DIRS}" >> $GITHUB_OUTPUT

  set-matrix2:
    runs-on: ubuntu-latest
    needs: set-matrix

    outputs:
      RUBY_VERSION: ${{ steps.set-matrix2.outputs.RUBY_VERSION }}
      RUBY_SHA: ${{ steps.set-matrix2.outputs.RUBY_SHA }}
      RUBY_DIRS: ${{ steps.set-matrix2.outputs.RUBY_DIRS }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: set-matrix2
        id: set-matrix2
        run: |
          echo "RUBY_VERSION='${{needs.set-matrix.outputs.RUBY_VERSION}}'" >> $GITHUB_OUTPUT
          echo "RUBY_SHA='${{needs.set-matrix.outputs.RUBY_SHA}}'" >> $GITHUB_OUTPUT
          echo "RUBY_DIRS=${{needs.set-matrix.outputs.RUBY_DIRS}}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: set-matrix2

    strategy:
      matrix:
        dir: ${{ fromJson(needs.set-matrix2.outputs.RUBY_DIRS) }}
        arch: ['linux/amd64', 'linux/arm64']

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: test
        run: |
          echo ${{ needs.set-matrix2.outputs.RUBY_VERSION }}
          echo ${{ needs.set-matrix2.outputs.RUBY_SHA }}
          echo ${{ matrix.dir }}
          echo ${{ matrix.arch }}
      # -
      #   name: ruby build
      #   uses: ./.github/workflows/build.yml
      #   with:
      #     RUBY_VERSION: ${{needs.set-matrix.outputs.RUBY_VERSION}}
      #     RUBY_SHA: ${{needs.set-matrix.outputs.RUBY_SHA}}
      #     RUBY_DIR: ${{matrix.dir}}

