name: "build and push ruby"

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Ruby Version"
        default: "3.3.3"
        options:
          - "2.3.8"
          - "2.6.6"
          - "2.6.8"
          - "2.7.2"
          - "2.7.6"
          - "2.7.7"
          - "2.7.8"
          - "3.0.5"
          - "3.0.6"
          - "3.1.3"
          - "3.1.4"
          - "3.2.1"
          - "3.2.2"
          - "3.3.0"
          - "3.3.1"
          - "3.3.2"
          - "3.3.3"

env:
  DOCKER_BUILDKIT: 1
  DISABLE_ASSET_SYNC: 1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ["bullseye", "slim-bullseye"]
        arch: ["amd64", "arm64"]

    env:
      GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Ruby version info
        id: ruby-info
        run: |
          RUBY_DIR=`cat versions.json | jq -r -c '.[] | select(.RUBY_VERSION == "${{ inputs.version }}") | .RUBY_DIR'`
          RUBY_MAJOR=`cat versions.json | jq -r -c '.[] | select(.RUBY_VERSION == "${{ inputs.version }}") | .RUBY_MAJOR'`
          RUBY_VERSION=`cat versions.json | jq -r -c '.[] | select(.RUBY_VERSION == "${{ inputs.version }}") | .RUBY_VERSION'`
          RUBY_SHA=`cat versions.json | jq -r -c '.[] | select(.RUBY_VERSION == "${{ inputs.version }}") | .sha256'`
          RUBY_DATE=`date +%Y-%m-%d`
          
          echo "RUBY_MAJOR=$RUBY_MAJOR" >> $GITHUB_OUTPUT
          echo "RUBY_VERSION=$RUBY_VERSION" >> $GITHUB_OUTPUT
          echo "RUBY_SHA=$RUBY_SHA" >> $GITHUB_OUTPUT
          echo "RUBY_DIR=$RUBY_DIR" >> $GITHUB_OUTPUT
          echo "TAG=${RUBY_VERSION}-${{ matrix.dir }}-${RUBY_DATE}" >> $GITHUB_OUTPUT


      # - name: Login to GitHub Container Registry
      #   run: |
      #     GITHUB_ID=`gh api user | jq -r ".login"`
      #     echo "${{ secrets.PERSONAL_GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ID --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.ruby-info.outputs.RUBY_DIR }}/${{ matrix.dir }}
          push: true
          tags: |
            ghcr.io/gendosu/ruby:${{ steps.ruby-info.outputs.TAG }}
            ghcr.io/gendosu/gentest:${{ steps.ruby-info.outputs.TAG }}
          platforms: linux/${{ matrix.arch }}
          build-args: |
            RUBY_MAJOR=${{ steps.ruby-info.outputs.RUBY_MAJOR }}
            RUBY_VERSION=${{ steps.ruby-info.outputs.RUBY_VERSION }}
            RUBY_DOWNLOAD_SHA256=${{ steps.ruby-info.outputs.RUBY_SHA }}