name: "build ruby starter"

on: push
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       type: choice
  #       description: "Ruby Version"
  #       options:
  #         - "2.7.x"
  #         - "2.7.7"
  #         - "3.0.8"

env:
  DOCKER_BUILDKIT: 1
  DISABLE_ASSET_SYNC: 1

jobs:
  set-matrix:
    runs-on: ubuntu-latest

    outputs:
      RUBY_DIR: ${{ steps.set-matrix.outputs.RUBY_DIR }}
      RUBY_MAJOR: ${{ steps.set-matrix.outputs.RUBY_MAJOR }}
      RUBY_VERSION: ${{ steps.set-matrix.outputs.RUBY_VERSION }}
      RUBY_SHA: ${{ steps.set-matrix.outputs.RUBY_SHA }}
      RUBY_BASES: ${{ steps.set-matrix.outputs.RUBY_BASES }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: set-matrix
        id: set-matrix
        run: |
          RUBY_DIR=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .RUBY_DIR'`
          RUBY_MAJOR=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .RUBY_MAJOR'`
          RUBY_VERSION=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .RUBY_VERSION'`
          RUBY_SHA=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .sha256'`
          RUBY_BASES=`cat versions.json | jq -c '.[] | select(.ruby == "2.7.7") | .base'`

          echo "RUBY_DIR='${RUBY_DIR}'" >> $GITHUB_OUTPUT
          echo "RUBY_MAJOR='${RUBY_MAJOR}'" >> $GITHUB_OUTPUT
          echo "RUBY_VERSION='${RUBY_VERSION}'" >> $GITHUB_OUTPUT
          echo "RUBY_SHA='${RUBY_SHA}'" >> $GITHUB_OUTPUT
          echo "RUBY_BASES=${RUBY_BASES}" >> $GITHUB_OUTPUT

  # set-matrix2:
  #   runs-on: ubuntu-latest
  #   needs: set-matrix

  #   outputs:
  #     RUBY_DIR: ${{ steps.set-matrix2.outputs.RUBY_DIR }}
  #     RUBY_MAJOR: ${{ steps.set-matrix2.outputs.RUBY_MAJOR }}
  #     RUBY_VERSION: ${{ steps.set-matrix2.outputs.RUBY_VERSION }}
  #     RUBY_SHA: ${{ steps.set-matrix2.outputs.RUBY_SHA }}
  #     RUBY_BASES: ${{ steps.set-matrix2.outputs.RUBY_BASES }}

  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #     -
  #       name: set-matrix2
  #       id: set-matrix2
  #       run: |
  #         echo "RUBY_DIR='${{needs.set-matrix.outputs.RUBY_DIR}}'" >> $GITHUB_OUTPUT
  #         echo "RUBY_MAJOR='${{needs.set-matrix.outputs.RUBY_MAJOR}}'" >> $GITHUB_OUTPUT
  #         echo "RUBY_VERSION='${{needs.set-matrix.outputs.RUBY_VERSION}}'" >> $GITHUB_OUTPUT
  #         echo "RUBY_SHA='${{needs.set-matrix.outputs.RUBY_SHA}}'" >> $GITHUB_OUTPUT
  #         echo "RUBY_BASES='${{needs.set-matrix.outputs.RUBY_BASES}}'" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: set-matrix

    strategy:
      matrix:
        dir: ${{ fromJson(needs.set-matrix.outputs.RUBY_BASES) }}
        arch: ['linux/amd64'] # 'linux/arm64'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: setup
        run: |
          echo "dir=" >> $GITHUB_OUTPUT

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: test
        run: |
          echo ${{needs.set-matrix.outputs.RUBY_VERSION}}
          echo ${{needs.set-matrix.outputs.RUBY_SHA}}
          echo ${{needs.set-matrix.outputs.RUBY_BASES}}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: 2.7/bullseye
      #     push: false
      #     tags: gendosu/gentest:${{ needs.set-matrix2.outputs.RUBY_VERSION }}-${{ needs.set-matrix2.outputs.RUBY_BASES }}
