name: "build"

on: 
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Ruby Version"
        options:
          - "2.7.4"
          - "3.0.2"

env:
  DOCKER_BUILDKIT: 1
  DISABLE_ASSET_SYNC: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [X86_64, ARM64]

    steps:
      - name: test
        run: |
          echo ${{ github.event.inputs.version }}
          # matrix
          echo ${{ matrix.arch }}
      # -
      #   name: Checkout
      #   uses: actions/checkout@v3
      # -
      #   # Add support for more platforms with QEMU (optional)
      #   # https://github.com/docker/setup-qemu-action
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: 2.7/bullseye
      #     push: true
      #     tags: gendosu/gentest:${{ github.event.inputs.env }}
