name: "sub_build"

on:
  workflow_call:
    inputs:
      RUBY_VERSION:
        required: true
        type: string
      RUBY_SHA:
        required: true
        type: string
      RUBY_DIR:
        required: true
        type: string

env:
  DOCKER_BUILDKIT: 1
  DISABLE_ASSET_SYNC: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: 2.7/bullseye
          push: false
          tags: gendosu/gentest:${{ github.event.inputs.env }}
